#!/usr/bin/python

def configure(ctx):
    SDL_FRAGMENT = """
        #include <SDL2/SDL.h>
        #undef main

        int main(int argc, char* argv[])
        {
            return 0;
        }
    """

    ctx.check(
        fragment=SDL_FRAGMENT,
        lib="SDL2",
        header_name="SDL2/SDL.h",
        libpath=[ ctx.path.find_node("lib").abspath() ],
        includes=[ ctx.path.find_node("include").abspath() ],
        uselib_store="sdl2"
    )

def build(ctx):
    dll_node = ctx.path.find_node("bin/SDL2.dll")
    bin_node = ctx.root.find_node(ctx.out_dir).make_node("bin")

    ctx(features="subst",
        is_copy=True,
        source=[ dll_node ],
        target=[ bin_node.make_node("SDL2.dll") ]
    )

