#!/usr/bin/python

def configure(ctx):
    libraries = [
        "avcodec",
        "avdevice",
        "avfilter",
        "avformat",
        "avresample",
        "avutil",
        "swresample",
        "swscale"
    ]
    ctx.check(
        lib=libraries,
        libpath=ctx.path.find_node("lib").abspath(),
        header_name="libavformat/avformat.h",
        includes=[
            ctx.path.find_node("include").abspath(),
            ctx.path.find_node("extra/includes").abspath()
        ],
        uselib_store="FFMPEG"
    )


def build(ctx):
    for lib in ctx.path.find_node("bin").ant_glob("*.dll"):
        ctx(features="subst",
            is_copy=True,
            target=str(lib),
            source=lib,
            path=ctx.root.find_node(ctx.out_dir).make_node("bin"),
            install_path="${BINDIR}"
        )
